Repository FLearningg/Flearning_BE, pull requests merged in 2025-07, with the labels that each got.

#45 [FLN-88][BE] Format code, add api update all readStatus, public api for admin and student
  BackEnd/controllers/notificationController.js
  BackEnd/routes/notificationRoutes.js
Labels: bug, HomePage and general

#48 [FLN-93][Thien][BE] Fix course details api
  BackEnd/controllers/courseDetailsController.js
  BackEnd/routes/courseRoutes.js
Labels: bug, course

#47 [FLN-92][BE] Add API to track Course Progress
  BackEnd/controllers/progressController.js
  BackEnd/routes/progressRoutes.js
  BackEnd/server.js
Labels: enhancement, Profile

#49 [Dat][API] Update Admin stats API
  BackEnd/controllers/adminController.js
  BackEnd/controllers/chatbotController.js
Labels: Admin

#51 [FLN-97][API][BE][Fix] Thay đổi có thể enroll nhiều course cùng lúc
  BackEnd/controllers/courseController.js
Labels: enhancement

#52 [FLN-68][Thien][BE] Add Payment API
  BackEnd/controllers/paymentController.js
  BackEnd/routes/courseRoutes.js
  BackEnd/routes/paymentRoutes.js
  BackEnd/server.js
Labels: payment

#55 [API] Mobile Forgot Password
  BackEnd/controllers/authController.js
  BackEnd/models/userModel.js
  BackEnd/routes/authRoutes.js
Labels: authentication

#60 [FLN][Duc][BE] Add API to calculate average rating for course
  BackEnd/controllers/feedbackController.js
  BackEnd/models/feedbackModel.js
  BackEnd/routes/feedbackRoutes.js
Labels: enhancement
